import type { Rule } from '@unocss/core'
import {
  alignments,
  appearance,
  appearances,
  aspectRatio,
  bgColors,
  borders,
  boxShadows,
  boxSizing,
  breaks,
  colorScheme,
  containerParent,
  contains,
  contents,
  contentVisibility,
  cssProperty,
  cssVariables,
  cursors,
  displays,
  fieldSizing,
  flexGridJustifiesAlignments,
  floats,
  fontSmoothings,
  fontStyles,
  gaps,
  insets,
  justifies,
  margins,
  opacity,
  orders,
  outline,
  overflows,
  paddings,
  placements,
  pointerEvents,
  positions,
  questionMark,
  resizes,
  rings,
  sizes,
  svgUtilities,
  tabSizes,
  textAligns,
  textDecorations,
  textIndents,
  textOverflows,
  textShadows,
  textStrokes,
  textTransforms,
  textWraps,
  transforms,
  transitions,
  userSelects,
  verticalAligns,
  whitespaces,
  willChange,
  zIndexes,
} from '@unocss/preset-mini/rules'
import type { Theme } from '../theme.js'
import { grids } from './grid.js'
import { flex } from './flex.js'
import { fonts } from './typography.js'
import { flow } from './flow.js'
import { container } from './container.js'

export const rules: Rule<Theme>[] = [
  cssVariables,
  cssProperty,
  contains,
  pointerEvents,
  appearances,
  positions,
  insets,
  zIndexes,
  orders,
  grids, // custom
  floats,
  margins,
  boxSizing,
  displays,
  aspectRatio,
  flow, // custom
  container, // custom
  sizes,
  flex, // custom
  transforms,
  cursors,
  userSelects,
  resizes,
  appearance,
  placements,
  alignments,
  justifies,
  gaps,
  flexGridJustifiesAlignments,
  overflows,
  textOverflows,
  whitespaces,
  breaks,
  borders,
  bgColors,
  colorScheme,
  svgUtilities,
  paddings,
  textAligns,
  textIndents,
  textWraps,
  verticalAligns,
  fonts, // custom
  textTransforms,
  fontStyles,
  textDecorations,
  fontSmoothings,
  tabSizes,
  textStrokes,
  textShadows,
  opacity,
  boxShadows,
  outline,
  rings,
  transitions,
  willChange,
  contentVisibility,
  contents,
  containerParent,
  fieldSizing,

  // should be the last
  questionMark,
].flat(1) as Rule<Theme>[]
